name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: 16
        
    - run: |
           cd /root/dmp
           rm -rf *
           docker stop test
           docker rm $(docker ps -aq)
           docker run -d -p 80:80 --name test nginx
           git pull
           docker cp index.html test:/usr/share/nginx/html
